### ISSUE TITLE
Project configuration should be parsed in Rust

### ISSUE THREAD

**Issue by emdoyle** [gauge-sh/tach#123]
While profiling Tach during #82 , I noticed that `parse_project_config` was taking ~100ms, even though it should be parsing a relatively tiny file into a relatively simple data structure. Instead of trying to improve this in Python, it makes more sense to just extract this to the Rust extension and use something like `serde`.

Either in the same PR or a separate one, it would also make sense to move the `dump_project_config_to_yml` into the Rust extension as well.

Ideally all of this can be done in a way that is minimally coupled to YML, since we may want to migrate to TOML in the future.

**Comment by ranjanmangla1** [comment]
@emdoyle can I take this one?

**Comment by emdoyle** [comment]
@ranjanmangla1 This one is also open! Do you want me to assign this one as well as #145 ?

**Comment by ranjanmangla1** [comment]
@emdoyle assign it, will love to take this one too

**Comment by caelean** [comment]
@ranjanmangla1 curious as to if you're still working on this one?

**Comment by caelean** [comment]
@ranjanmangla1 going to open this one back up for other folks
