### ISSUE TITLE
Support file globbing in exclude_paths

### ISSUE THREAD

**Issue by emdoyle** [gauge-sh/tach#124]
As mentioned in #101, it's confusing that `exclude_paths` uses regex instead of file globbing.

Conceptually, this behavior should match that of other linters like ruff. Using that example, it makes sense to support `globset`:
https://docs.astral.sh/ruff/settings/#exclude
https://docs.rs/globset/latest/globset/#syntax

This will require updating the docs to explain the new behavior.

**Comment by emdoyle** [comment]
> hey @emdoyle I would love to work on this issue. since, its good first issue 👍

Sounds great! Feel free to put up a PR any time, and ask me if anything is unclear.

**Comment by emdoyle** [comment]
@shreyash2002 is this still something you'd like to work on? Otherwise I'll unassign so that someone else can pick it up.

**Comment by legendkartik45** [comment]
Hi @emdoyle,

Is this issue still open? If so, could you please assign it to me? I would love to work on it over the weekend!

**Comment by emdoyle** [comment]
@legendkartik45 That would be great, thanks! I might also recommend basing your branch on #208 to avoid significant merge conflicts when your changes are ready.

**Comment by caelean** [comment]
Hey @legendkartik45! Are you still working on this issue?

**Comment by caelean** [comment]
@legendkartik45 going to open this one back up for other folks

**Comment by architgarg** [comment]
I tried fixing this issue here - https://github.com/gauge-sh/tach/pull/234

**Comment by sparshg** [comment]
Resolved in #259
