### ISSUE TITLE
`tach.logging.logger` includes a function os.fork() which is only available in unix-based system

### ISSUE THREAD

**Issue by dhananjaypai08** [gauge-sh/tach#134]
I am using tach on my windows OS, and whenever I use to run any tach command it gives me this error
```
Process Process-1:
Traceback (most recent call last):
  File "C:\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\dhana\AppData\Roaming\Python\Python312\site-packages\tach\logging\logger.py", line 48, in handle_log_entry
    if os.fork() != 0:
       ^^^^^^^
AttributeError: module 'os' has no attribute 'fork'
Validation error: Module 'C:\Users\dhana\coding\Personal Projects\DeCATv\lucas\tach\python' is not contained within source root: 'C:\Users\dhana\coding\Personal Projects\DeCATv\lucas\tach\python'
```
I think this is because in the `tach.logging.logger::handle_log_entry`, the try catch block is does not catch the AttributeError( Indicates not unix-like OS).
I have resolved this for my own use by re-building the tach module by appending a catch for the `AttributeError`, this removed the error message and works fine. One other way would be to detect the OS using platform module and only then call the os.fork() function but not feasible for this stage. Also, should I raise a PR on this?

**Comment by emdoyle** [comment]
Thanks for raising this! Please do create a PR with your change, the intention was to silently fail on Windows systems but it looks like the catch block was incorrect. The fix can go out in the next version.
