### ISSUE TITLE
tech.yml JSON Schema

### ISSUE THREAD

**Issue by devova** [gauge-sh/tach#142]
Is there any JSON schema published for `tach.yml`? It would be useful to have one and assign it in IDEs for auto completion and validation.

**Comment by emdoyle** [comment]
Thanks for raising this! Check out #143 for the details, you should be able to use the URL: https://gauge-sh.github.io/tach/assets/tach-yml-schema.json

**Comment by devova** [comment]
just tested it in PyCharm - works like a magic, thanks a lot, and thanks for the project

**Comment by emdoyle** [comment]
> just tested it in PyCharm - works like a magic, thanks a lot, and thanks for the project

@devova Hi! Just an update, we are moving our docs to [docs.gauge.sh](https://docs.gauge.sh) using Mintlify, so we will eventually take down the original URL (https://gauge-sh.github.io is our GitHub pages documentation site).

Instead, please use: https://raw.githubusercontent.com/gauge-sh/tach/v0.6.8/public/tach-yml-schema.json
which is a versioned link to the schema file in our repo. Thanks!
