### ISSUE TITLE
Graphviz graph export

### ISSUE THREAD

**Issue by 13hannes11** [gauge-sh/tach#144]
It would be great to have the ability to generate a dependency graph based on the `tach.yml` file in graphviz format. 

See Graphviz [example](https://graphviz.org/Gallery/directed/go-package.html)). Tach could simply just output a graphviz file to stdout.
![](https://graphviz.org/Gallery/directed/go-package.svg)

## Optional features
- Shows the difference between the config and the actual source code. (togglable via commandline flags)
  - Violations are marked
  - Imports that are in `tach.yml` but do not exist in the code base are marked

**Comment by 13hannes11** [comment]
Nevermind I somehow missed the show in the readme

**Comment by caelean** [comment]
Hi @13hannes11! Tach can currently do a version of this with [tach show](https://gauge-sh.github.io/tach/usage/#tach-show)

Right now the graph is generated remotely to avoid heavy dependencies getting added to tach. There's also many more interactive features we can build into the visualization through a web ui, including the ones you mentioned as optional. Let me know if this satisfies your usecase!

Here's `tach show` run on Tach: 

<img width="1550" alt="tach_show" src="https://github.com/gauge-sh/tach/assets/5150563/f035a9e5-2076-463c-a46c-5c18485f2edf">

**Comment by 13hannes11** [comment]
I'd prefer an option that is not dependent on a web ui. The graphviz format is not too complicated and thus I do not really see additional depedency requirements. Of course it should also not be too difficult to build an external conversion tool

**Comment by caelean** [comment]
@13hannes11 given our core focus is on expanding web capabilities at the moment, I'm going to leave this closed out. However, if you want to give adding graphviz support a go, feel free to put up a pr! We're happy to accept that as an expansion on current functionality. 

Let us know if there are any other features you'd like to see, and join the conversation on [Discord](https://discord.gg/a58vW8dnmw) 😄
