### ISSUE TITLE
sync should delete modules which do not exist

### ISSUE THREAD

**Issue by emdoyle** [gauge-sh/tach#145]
To see this behavior, you can add:
```
- path: notarealmodule
  depends_on: []
...
```
into your `tach.yml`, and then run  `tach sync`.

Right now, the module `notarealmodule` will remain in the `tach.yml` file.
This PR should instead remove all modules listed which cannot be resolved from the configured source root.

**Comment by ranjanmangla1** [comment]
@emdoyle is it still open?

**Comment by emdoyle** [comment]
@ranjanmangla1 Yes!

**Comment by dhananjaypai08** [comment]
Hi @emdoyle , haven't we depreciated the `--prune` command and have introduced `--add`?

**Comment by tiluckdave** [comment]
@emdoyle Should I take this one?

**Comment by emdoyle** [comment]
> @emdoyle Should I take this one?

That would be great, thanks!
