### ISSUE TITLE
Add setting to fail 'tach check' if circular dependencies exist

### ISSUE THREAD

**Issue by emdoyle** [gauge-sh/tach#146]
Some projects would like to ensure that their project's dependencies remain unidirectional, or in other words, that there are no cycles in their dependency graph.

A simple way to begin supporting this is to add a setting like `forbid_circular_dependencies` which can be set in `tach.yml` (`ProjectConfig` within the Tach codebase). When this setting is true, `tach check` should fail with a specific error message when a circular dependency is detected.

This should likely be done as a "pre-flight check" which would validate the `modules` list, and could be delegated to the `ModuleTree` internally. It does not need to apply any new logic to actual detected imports.

**Comment by tiluckdave** [comment]
Hey @emdoyle can I give this one a try next?

**Comment by emdoyle** [comment]
Absolutely!
