### ISSUE TITLE
Make --prune the default behavior of tach sync

### ISSUE THREAD

**Issue by emdoyle** [gauge-sh/tach#147]
Right now, the default behavior of `sync` is additive, meaning that it will not remove any modules or configured dependencies. Instead it will add dependencies to existing modules to fix any boundary errors detected.

When using the `--prune` option, `sync` ignores the currently configured dependencies, and instead sets the dependencies for each module to the minimal set matching the actual imports found in the codebase. This behavior is more consistent with the idea of "syncing" your dependencies, and should be the default behavior when calling `tach sync` with no CLI arguments.

The current additive behavior should be enabled by passing a renamed flag: `--add`
That is, `tach sync` will prune dependencies to the minimal set, while `tach sync --add` will add any missing dependencies.

NOTE: This issue interacts with #145 , and may require coordination if both are worked on simultaneously

**Comment by dhananjaypai08** [comment]
@emdoyle  The basic idea is to actually reverse the working, right? Where we had `--prune` as an argument to `tach sync` command this would call the `sync::prune_dependency_constraints` if `--prune` was true. Now we can have a diff argument called `--add` and whenever that is set to true we will just ignore calling the `sync::prune_dependency_constraints`. Is this the right way of thinking for this issue?
