### ISSUE TITLE
Maintain formatting and language server directive in tach.yml after sync

### ISSUE THREAD

**Issue by emdoyle** [gauge-sh/tach#150]
Right now, the `tach.yml` in our repo is formatted with 2 space indents at each level of nesting, and there is a language server comment directive at the top of the file.

After running any variant of `tach sync` however, the language server directive is eliminated, and the formatting reverts to be minimally indented.

It would be much nicer if `tach sync` could preserve formatting, but at a minimum it should preserve the language server directive.

**Comment by tiluckdave** [comment]
Hey @emdoyle 
I would like to work on this issue. Could you please assign this to me!
