### ISSUE TITLE
Add deprecated modifier to file

### ISSUE THREAD

**Issue by 13hannes11** [gauge-sh/tach#184]
I have the following use case:

I want to slowly introduce tach and thus slowly remove depends_on from some modules. If I add a comment in the tach.yml it gets overwritten by sync so desirable behaviour for me would be:

Either:
- Do not delete comments
- Have a deprecation annotation 
  - tach could support checking violations with all deprecated dependencies removed and without them being removed)
  - automatically remove deprecation annotations on sync if the dependency is not present anymore

**Comment by emdoyle** [comment]
Hi @13hannes11 thanks for raising this!

Preserving comments definitely makes sense. I would imagine we could store information about comment locations on the ProjectConfig up-front during parsing, and then use them while dumping the ProjectConfig to yml. I'm not sure how complex it might be to cover edge cases but it seems doable, at least for comments that live on their own line (trailing comments on lines that change seem complicated). I'll add this as a ticket to our internal tracking system and ping back here when it's shipped.

For the deprecation annotation, could you tell me more about your use case? Is your workflow similar to #187 in the sense that you are trying to gradually phase out a specific dependency?

**Comment by 13hannes11** [comment]
> For the deprecation annotation, could you tell me more about your use case? Is your workflow similar to #187 in the sense that you are trying to gradually phase out a specific dependency?

That's exactly the use case I was thinking of.

**Comment by caelean** [comment]
Hi @13hannes11! Sorry for the delay, I'm working on this now

**Comment by caelean** [comment]
@13hannes11 this is shipped! Upgrade to `0.9.0` and check out https://docs.gauge.sh/usage/deprecate
