### ISSUE TITLE
Filter dependencies in tach report

### ISSUE THREAD

**Issue by nip3o** [gauge-sh/tach#187]
I'm in the process of untangling the dependencies of a project, and trying to figure out why a certain module, say `utils`, depend on another module, say `blog`. The goal is to remove `blog` from the `depends_on:` list of `utils`. 

The most helpful way I have found is to comment out `blog` from the `depends_on:` list of `utils` and then run `tach check` to get a list of modules that causes that dependency. This is a bit cumbersome though. 

Would it be possible to add something like a `--filter` option to `tach report` to only show dependencies of a certain module (i.e. `tach report utils --filter=blog`) to achieve the same the same goal? Right now `tach report` lists every single dependency, including dependencies within the module itself, which is just too much output to be useful.

**Comment by emdoyle** [comment]
This makes sense, and your use case with commenting out a dependency is one I see all the time. This should be a straightforward addition! I can tackle this after #171
