### ISSUE TITLE
Support for PEP 420 Implicit Namespace Packages

### ISSUE THREAD

**Issue by malcolmgreaves** [gauge-sh/tach#203]
Hello! 👋 Thank you for making and distributing `tach`! ❤️ 

Does `tach` support [namespace packages](https://peps.python.org/pep-0420/)? 🤔 I did not see explicit support in the docs. And I've been running into issues trying to adapt `tach` to my situation. I'd like to use `tach` in a project that makes use of multiple namespace packages. 

The individual packages are all PEP-420 compliant. There is a specific set of inter-dependencies that must be enforced between the namespaced packages. This DAG is currently encoded in each's own `install_requires`. However, I'd like to use `tach` to further enforce and check that these inter-namespace package dependencies are (a) all what we intend and (b) identify and flag any module boundary violations. It'd be great if `tach` would also inspect the `install_requires` and verify that the dependency graph is correct too. Here, "module" really means "distinct namespace package." Though I think the concepts are well aligned :)

Is this something that is in the near-future for `tach`?

**Comment by malcolmgreaves** [comment]
Also, I think that this issue is quite related: https://github.com/gauge-sh/tach/issues/192 I did not want to distract from that individual's issue by bringing up explicit PEP-420 support. But perhaps a solution can work for both issues?

**Comment by emdoyle** [comment]
This is now supported natively in `0.9.0`!
https://docs.gauge.sh/usage/configuration#source-roots
