### ISSUE TITLE
`tach check` reporting import error on excluded files

### ISSUE THREAD

**Issue by sparshg** [gauge-sh/tach#261]
`tach mod`:

```
Confirm Your Modules                                                                      │
│└── [Source Root] manim ∨                                                                │
│    └── [Module] manim ∨                                                                 │
│        ├── -> [Module] _config ∨                                                        │
│        │   ├── cli_colors.py                                                            │
│        │   ├── logger_utils.py                                                          │
│        │   └── utils.py                                                                 │
│        ├── [Module] animation > 
```

`tach sync` would generate entry for

```
[[modules]]
path = "manim._config"
depends_on = [
    { path = "manim" },
    { path = "manim.mobject" },
    { path = "manim.utils" },
]
```

If I delete `{ path = "manim"}` I get
> ❌ manim/_config/utils.py[L29]: Cannot import 'manim.constants'. Module 'manim._config' cannot depend on 'manim'. 

but my excludes have `manim/constants.py`

The problem is that the imports don't get checked if they are in an excluded file or not.

Is this intended behaviour?

**Comment by emdoyle** [comment]
This is a bug, thanks for raising this! From browsing the related code, it looks to me like a regression introduced when we started using absolute paths for checking exclusion. I'll add a test for this case and make a fix.
