### ISSUE TITLE
`tag show` export to mermaid locally

### ISSUE THREAD

**Issue by h0uter** [gauge-sh/tach#276]
It would be practical if we can export locally to Mermaid in addition to graphviz `.dot`. I see the web version (`tach show --web`) already renders to Mermaid. This would make it possible to auto-update diagrams in a README.md for example.

There also exist tools to convert dot to mermaid: https://github.com/monitorian/dot2mermaid

**Comment by emdoyle** [comment]
This makes sense! It will likely ship by the end of this week.

**Comment by tiluckdave** [comment]
Yeah sure

**Comment by h0uter** [comment]
Would be useful if in addition to saving to file we can directly pipe the output of ’tach show’ to the command line so we can use it with find and replace utilities (like ’sed’) to directly replace a section of an existing Readme in CI/CD.

**Comment by tosoham** [comment]
Okay, I'll see what can I do.
