### ISSUE TITLE
Check-external also warn on unused dependencies?

### ISSUE THREAD

**Issue by gwdekker** [gauge-sh/tach#294]
Hey, I was wondering if check-external could also warn or report the case in which an external dependency is declared in pyproject.toml, but not seems to be used anywhere in the source code? This tends to happen to projects that evolve over time, where some functionality got removed but it was forgotten to update the dependencies. Classic linters would of course typically pick up dependencies imported at the top of a `.py` file but not used in the file, but not on the more general case sketched above, while I would expect that `tach` could do this easily given the parsing already needed for `check-external`?

**Comment by emdoyle** [comment]
This would be straightforward, should be out in a release in the next couple days!
