### ISSUE TITLE
suggestion: redirect gauge.sh/docs to docs.gauge.sh and add a hyperlink from gauge.sh to docs.gauge.sh

### ISSUE THREAD

**Issue by cameronbrill** [gauge-sh/tach#413]
FYI I wanted to RTFM and noticed that i can't get to the docs page easily from your website

**Comment by caelean** [comment]
Hi @cameronbrill - thanks for the note - I've added a redirect from `gauge.sh/docs` -> `docs.gauge.sh`!

We're in the process of redoing our main website; I'll be sure to more directly link to the docs as a part of that effort as well. Thanks for the tip!
