### ISSUE TITLE
Centralized configuration from pyproject.toml

### ISSUE THREAD

**Issue by tclasen** [gauge-sh/tach#49]
One of my main complaints about the JavaScript ecosystem is the root of the project is cluttered with hundreds of individual tool-specific configuration files, python has mostly been able to avoid this by centralizing most configuration to the pyproject.toml file.

I would like to be able to configure tach entirely from the pyproject.toml file.

Potential implementation details: It is possible (and maybe even common?) for someone to use both pyproject.toml and the existing configuration files. There should be a single, correct, determinstic way to load and merge configs from all these files. In most projects that do this the pyproject.toml file is loaded first, and the tach-specific config files overlay on top of them if they are present.

Potential issues: Native ability to read TOML files only recently came to the python standard library, for older versions you will have to bring in another 3rd-party dependency.

Example from another tool: https://import-linter.readthedocs.io/en/stable/toml.html#toml-support

**Comment by emdoyle** [comment]
@tclasen @rossmacarthur

I can definitely understand wanting a central place for config, I built a quick version in #55 but wasn't happy with the resulting central TOML syntax (highly verbose) or the additional complexity given there are now several `tach` commands that write and modify config files which would need to handle all-YML, all-TOML, or mixed-config cases. We're going to stick with the current configuration for now but revisit this in the near future, I explain more in the PR close comment in #55
