### ISSUE TITLE
VSCode Extension for Import Linting

### ISSUE THREAD

**Issue by max-muoto** [gauge-sh/tach#57]
It would be great if there was a VSCode extension to help with live import linting, similar to what Pylance or the Ruff LSP can do. This way boundaries being broken can be be caught earlier as opposed to later. I wonder if it might be possible to point the CLI tool against the file whenever a module is saved, some plugins do this without taking any advantage of an LSP, for example https://github.com/InSyncWithFoo/pyright-for-pycharm (not VSCode, but the same idea)

**Comment by caelean** [comment]
Thanks for the issue @max-muoto! We're working on adding IDE linting support 👍
